block_weather.settings:
  type: config_object
  label: 'Block Weather settings'
  mapping:
    api_key:
      type: string
      label: 'API key for the weather service.'
    city:
      type: label
      label: 'City for which the weather data will be displayed.'
